class st{#Nt=0;#l=null;#ci=[];#sz="M";static API="https://orican-printify.vercel.app";static RATIO=4200/4800;static SIZES=["XS","S","M","L","XL","2XL","3XL","4XL","5XL"];static TEES=[{name:"Crew tee",price:"$14.00"},{name:"V-neck tee",price:"$14.00"},{name:"Heavy crew tee",price:"$15.00"}];
static esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c])}
static load(){let d=[];try{d=JSON.parse(document.getElementById("orican-products").textContent)}catch(e){}
return(Array.isArray(d)?d:[]).filter(p=>p&&Array.isArray(p.variants)&&p.variants.length).map(p=>{const hex=p.meta&&p.meta.colors||{},names=[];for(const v of p.variants)names.includes(v.c)||names.push(v.c);const ord=Object.keys(hex);names.sort((a,b)=>(ord.indexOf(a)+1||999)-(ord.indexOf(b)+1||999));
return{live:!0,name:String(p.title||"").replace(/^ORICAN\s+/i,""),variants:p.variants,palette:names.map(c=>({name:c,value:c,hex:hex[c]||"#cccccc"}))}})}
constructor(t){this.el=t;this.track=t.querySelector(".blank-track");this.nameEl=t.querySelector("#teeName");this.priceEl=t.querySelector("#teePrice");this.btn=t.querySelector(".openFrame");this.fav=t.querySelector(".fav");this.colorHost=t.querySelector(".cs-host");this.sizeHost=t.querySelector(".size-host");
const dotsHost=t.querySelector(".blank-dots");this.products=st.load();
if(this.products.length){const n=this.products.length;this.track.innerHTML=this.products.map((p,i)=>'<div class="blank-slide" role="group" aria-roledescription="slide" aria-label="'+st.esc(p.name)+", "+(i+1)+" of "+n+'"><img class="blank-img" alt="'+st.esc(p.name)+'" draggable="false" decoding="async"'+(i?' loading="lazy"':"")+"></div>").join("");dotsHost.innerHTML=this.products.map(p=>'<button class="blank-dot" aria-label="'+st.esc(p.name)+'"></button>').join("")}
else this.products=st.TEES.map(e=>({live:!1,name:e.name,price:e.price,variants:[],palette:X.map(c=>({name:c.name,value:c.name,hex:c.hex})),sizes:["S","M","L","XL"]}));
this.slides=[...this.track.children];this.tees=Array.from(t.querySelectorAll(".tee"));this.dots=Array.from(dotsHost.querySelectorAll(".blank-dot"));this.saved=this.products.map(()=>!1);
t.querySelector(".blank-prev").addEventListener("click",()=>this.go(this.#Nt-1)),t.querySelector(".blank-next").addEventListener("click",()=>this.go(this.#Nt+1)),this.dots.forEach((e,i)=>e.addEventListener("click",()=>this.go(i))),this.fav.addEventListener("click",()=>{this.saved[this.#Nt]=!this.saved[this.#Nt],this.#H()});
const e=t.querySelector(".blank-stage");e.setAttribute("tabindex","0"),e.addEventListener("keydown",t=>{"ArrowLeft"===t.key?this.go(this.#Nt-1):"ArrowRight"===t.key&&this.go(this.#Nt+1)}),e.addEventListener("pointerdown",t=>{t.target.closest("button")||(this.#l={x:t.clientX})}),e.addEventListener("pointerup",t=>{const e=this.#l;if(!e)return;this.#l=null;const s=t.clientX-e.x;Math.abs(s)>40&&this.go(this.#Nt+(s<0?1:-1))}),e.addEventListener("pointercancel",()=>{this.#l=null});
document.addEventListener("orican:next",t=>{this.#cart(t.detail)});this.#build(),this.#H()}
get product(){return this.products[this.#Nt]}get color(){return this.select.color}get size(){return this.sizeSelect.color}get tee(){const p=this.product,v=this.variant;return{name:p.name,price:v?v.money:p.price||""}}
get variant(){const p=this.product;if(!p.live)return null;const c=this.color.name;return p.variants.find(v=>v.c===c&&v.s===this.#sz)||null}
go(t){this.el.classList.remove("is-open"),this.#Nt=N(t,this.products.length),this.#build(),this.#H()}
#sizes(){const p=this.product;if(!p.live)return p.sizes.slice();const c=this.color.name,s=[];for(const v of p.variants)v.c!==c||s.includes(v.s)||s.push(v.s);return s.sort((a,b)=>st.SIZES.indexOf(a)-st.SIZES.indexOf(b))}
#picker(host,opts){host.replaceChildren(),host.className=host.classList.contains("size-host")?"size-host":"cs-host";return new Z(host,{...opts,onOpen:()=>this.el.classList.add("is-open"),onClose:()=>this.el.classList.remove("is-open")})}
#build(){const p=this.product,i=Math.min(this.#ci[this.#Nt]||0,p.palette.length-1);this.select=this.#picker(this.colorHost,{items:p.palette,value:p.palette[i].value,label:"Tee color",onChange:t=>{this.#ci[this.#Nt]=p.palette.indexOf(t),this.#buildSize(),this.#H()}}),this.#buildSize()}
#buildSize(){const s=this.#sizes();s.includes(this.#sz)||(this.#sz=s.includes("M")?"M":s[0]);this.sizeSelect=this.#picker(this.sizeHost,{items:s.map(t=>({name:t,value:t})),kind:"text",noun:"Size",value:this.#sz,label:"Tee size",onChange:t=>{this.#sz=t.value,this.#H()}})}
#img(i){const p=this.products[i];if(!p.live)return null;const c=p.palette[Math.min(this.#ci[i]||0,p.palette.length-1)].name,v=p.variants.find(t=>t.c===c&&t.img);return v?v.img:null}
#H(){const p=this.product,t=this.tee;this.track.style.transform=`translateX(${100*-this.#Nt}%)`,this.nameEl.textContent=t.name,this.priceEl.textContent=t.price,this.dots.forEach((e,i)=>e.setAttribute("aria-current",i===this.#Nt?"true":"false"));
this.slides.forEach((e,i)=>{const s=e.querySelector(".blank-img");if(!s)return;const u=this.#img(i);u&&s.getAttribute("src")!==u&&(s.src=u)});p.live||this.tees.forEach(e=>{e.style.color=this.color.hex});
this.btn.disabled=!!p.live&&!this.variant;const e=this.saved[this.#Nt];this.fav.setAttribute("aria-pressed",e),V(this.fav.firstElementChild,e?"mdi:heart":"mdi:heart-outline"),this.fav.setAttribute("aria-label",(e?"Remove ":"Save ")+p.name)}
static async pad(b){const i=await createImageBitmap(b),r=st.RATIO;let w=i.width,h=i.height,W=w,H=h;w/h>r?H=Math.round(w/r):W=Math.round(h*r);const c=document.createElement("canvas");c.width=W,c.height=H,c.getContext("2d").drawImage(i,Math.round((W-w)/2),Math.round((H-h)/2));return new Promise((t,e)=>c.toBlob(s=>s?t(s):e(new Error("png")),"image/png"))}
async #cart(d){const say=t=>setTimeout(()=>{const e=document.getElementById("textToast");document.getElementById("textToastText").textContent=t,e.classList.add("show"),clearTimeout(this.#l2),this.#l2=setTimeout(()=>e.classList.remove("show"),3200)},0),v=this.variant,b=document.getElementById("textNextBtn");
if(!v||!d||!d.imageBlob)return void say(v?"Couldn't prepare the image":"This tee can't be ordered yet");const html=b.innerHTML;b.disabled=!0,b.textContent="Adding to cart…";
try{const png=await st.pad(d.imageBlob),{upload:u}=await import(st.API+"/orican-upload.js"),r=await u("designs/"+v.id+".png",png,{access:"public",handleUploadUrl:st.API+"/api/upload",contentType:"image/png"}),root=window.Shopify&&Shopify.routes&&Shopify.routes.root||"/",
a=await fetch(root+"cart/add.js",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({items:[{id:v.id,quantity:1,properties:{Design:"Custom ORICAN proof",_design_url:r.url}}]})});
if(!a.ok){const e=await a.json().catch(()=>({}));throw new Error(e.description||e.message||"cart "+a.status)}location.href=root+"cart"}catch(e){console.error("ORICAN add to cart",e),b.disabled=!1,b.innerHTML=html,say("Couldn't add to cart. Please try again.")}}
#l2=0}
