class st{#Nt=0;#l=null;#ci=[];#sz="M";#dv=0;#cache=new Map;#masks=new Map;#tok=0;static API="https://orican-printify.vercel.app";static RATIO=4200/4800;static SIZES=["XS","S","M","L","XL","2XL","3XL","4XL","5XL"];static TEES=[{name:"Crew tee",price:"$14.00"},{name:"V-neck tee",price:"$14.00"},{name:"Heavy crew tee",price:"$15.00"}];
static AREA={"orican-crew-tee":[.3273,.2918,.3453,.3947],"orican-heavy-crew-tee":[.3253,.2969,.3494,.3993],"orican-v-neck-tee":[.3321,.3021,.3349,.3828]};
static esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[c])}
static load(){let d=[];try{d=JSON.parse(document.getElementById("orican-products").textContent)}catch(e){}
return(Array.isArray(d)?d:[]).filter(p=>p&&Array.isArray(p.variants)&&p.variants.length).map(p=>{const hex=p.meta&&p.meta.colors||{},names=[];for(const v of p.variants)names.includes(v.c)||names.push(v.c);const ord=Object.keys(hex);names.sort((a,b)=>(ord.indexOf(a)+1||999)-(ord.indexOf(b)+1||999));
return{live:!0,handle:p.handle,name:String(p.title||"").replace(/^ORICAN\s+/i,""),variants:p.variants,palette:names.map(c=>({name:c,value:c,hex:hex[c]||"#cccccc"}))}})}
static img(u){const i=new Image;i.crossOrigin="anonymous",i.decoding="async",i.src=u;return i.decode().then(()=>i)}
static async pad(b){const i=await createImageBitmap(b),r=st.RATIO;let w=i.width,h=i.height,W=w,H=h;w/h>r?H=Math.round(w/r):W=Math.round(h*r);const c=document.createElement("canvas");c.width=W,c.height=H,c.getContext("2d").drawImage(i,Math.round((W-w)/2),Math.round((H-h)/2));return new Promise((t,e)=>c.toBlob(s=>s?t(s):e(new Error("png")),"image/png"))}
static cut(img){const W=img.naturalWidth,H=img.naturalHeight,c=document.createElement("canvas");c.width=W,c.height=H;const g=c.getContext("2d",{willReadFrequently:!0});g.drawImage(img,0,0);const d=g.getImageData(0,0,W,H).data,n=W*H,L=new Uint8Array(n),bg=new Uint8Array(n),stk=new Int32Array(n),a=new Uint8ClampedArray(n);let sp=0;
for(let p=0,i=0;p<n;p++,i+=4)L[p]=54*d[i]+183*d[i+1]+19*d[i+2]>>8;const push=p=>{bg[p]||L[p]<232||(bg[p]=1,stk[sp++]=p)};
for(let x=0;x<W;x++)push(x),push((H-1)*W+x);for(let y=0;y<H;y++)push(y*W),push(y*W+W-1);
for(;sp;){const p=stk[--sp],x=p%W;x>0&&push(p-1),x<W-1&&push(p+1),p>=W&&push(p-W),p<n-W&&push(p+W)}
for(let p=0;p<n;p++){if(bg[p])continue;const x=p%W,e=x>0&&bg[p-1]||x<W-1&&bg[p+1]||p>=W&&bg[p-W]||p<n-W&&bg[p+W];a[p]=e?Math.max(0,Math.min(255,(250-L[p])*1.5)):255}return{a,W,H}}
constructor(t){this.el=t;this.track=t.querySelector(".blank-track");this.nameEl=t.querySelector("#teeName");this.priceEl=t.querySelector("#teePrice");this.btn=t.querySelector(".openFrame");this.fav=t.querySelector(".fav");this.colorHost=t.querySelector(".cs-host");this.sizeHost=t.querySelector(".size-host");
const dotsHost=t.querySelector(".blank-dots");this.products=st.load();
if(this.products.length){const n=this.products.length;this.track.innerHTML=this.products.map((p,i)=>'<div class="blank-slide" role="group" aria-roledescription="slide" aria-label="'+st.esc(p.name)+", "+(i+1)+" of "+n+'"><img class="blank-img" alt="'+st.esc(p.name)+'" draggable="false" data-ready="0"></div>').join("");dotsHost.innerHTML=this.products.map(p=>'<button class="blank-dot" aria-label="'+st.esc(p.name)+'"></button>').join("")}
else this.products=st.TEES.map(e=>({live:!1,name:e.name,price:e.price,variants:[],palette:X.map(c=>({name:c.name,value:c.name,hex:c.hex})),sizes:["S","M","L","XL"]}));
this.slides=[...this.track.children];this.tees=Array.from(t.querySelectorAll(".tee"));this.dots=Array.from(dotsHost.querySelectorAll(".blank-dot"));this.saved=this.products.map(()=>!1);
this.note=document.createElement("p"),this.note.className="cart-note",this.note.setAttribute("role","status"),this.priceEl.after(this.note);
this.addBtn=document.createElement("button"),this.addBtn.type="button",this.addBtn.className="btn add-cart",this.addBtn.hidden=!0,this.addBtn.textContent="Add to cart",this.btn.after(this.addBtn),this.addBtn.addEventListener("click",()=>this.#cart());
this.btnText=[...this.btn.childNodes].reverse().find(e=>e.nodeType===3&&e.nodeValue.trim());
t.querySelector(".blank-prev").addEventListener("click",()=>this.go(this.#Nt-1)),t.querySelector(".blank-next").addEventListener("click",()=>this.go(this.#Nt+1)),this.dots.forEach((e,i)=>e.addEventListener("click",()=>this.go(i))),this.fav.addEventListener("click",()=>{this.saved[this.#Nt]=!this.saved[this.#Nt],this.#H()});
const e=t.querySelector(".blank-stage");e.setAttribute("tabindex","0"),e.addEventListener("keydown",t=>{"ArrowLeft"===t.key?this.go(this.#Nt-1):"ArrowRight"===t.key&&this.go(this.#Nt+1)}),e.addEventListener("pointerdown",t=>{t.target.closest("button")||(this.#l={x:t.clientX})}),e.addEventListener("pointerup",t=>{const e=this.#l;if(!e)return;this.#l=null;const s=t.clientX-e.x;Math.abs(s)>40&&this.go(this.#Nt+(s<0?1:-1))}),e.addEventListener("pointercancel",()=>{this.#l=null});
document.addEventListener("orican:next",t=>{this.#design(t.detail)});this.#build(),this.#H()}
get product(){return this.products[this.#Nt]}get color(){return this.select.color}get size(){return this.sizeSelect.color}get tee(){const p=this.product,v=this.variant;return{name:p.name,price:v?v.money:p.price||""}}
get variant(){const p=this.product;if(!p.live)return null;const c=this.color.name;return p.variants.find(v=>v.c===c&&v.s===this.#sz)||null}
go(t){this.el.classList.remove("is-open"),this.#Nt=N(t,this.products.length),this.#build(),this.#H()}
#sizes(){const p=this.product;if(!p.live)return p.sizes.slice();const c=this.color.name,s=[];for(const v of p.variants)v.c!==c||s.includes(v.s)||s.push(v.s);return s.sort((a,b)=>st.SIZES.indexOf(a)-st.SIZES.indexOf(b))}
#picker(host,opts){host.replaceChildren(),host.className=host.classList.contains("size-host")?"size-host":"cs-host";return new Z(host,{...opts,onOpen:()=>this.el.classList.add("is-open"),onClose:()=>this.el.classList.remove("is-open")})}
#build(){const p=this.product,i=Math.min(this.#ci[this.#Nt]||0,p.palette.length-1);this.select=this.#picker(this.colorHost,{items:p.palette,value:p.palette[i].value,label:"Tee color",onChange:t=>{this.#ci[this.#Nt]=p.palette.indexOf(t),this.#buildSize(),this.#H()}}),this.#buildSize()}
#buildSize(){const s=this.#sizes();s.includes(this.#sz)||(this.#sz=s.includes("M")?"M":s[0]);this.sizeSelect=this.#picker(this.sizeHost,{items:s.map(t=>({name:t,value:t})),kind:"text",noun:"Size",value:this.#sz,label:"Tee size",onChange:t=>{this.#sz=t.value,this.#H()}})}
#colorOf(i){const p=this.products[i];return p.palette[Math.min(this.#ci[i]||0,p.palette.length-1)].name}
#mask(i){if(this.#masks.has(i))return this.#masks.get(i);const p=this.products[i],lum=t=>{const h=(p.palette.find(c=>c.name===t.c)||{}).hex||"#888888";return parseInt(h.slice(1,3),16)+parseInt(h.slice(3,5),16)+parseInt(h.slice(5,7),16)},dark=p.variants.find(v=>v.c==="Black"&&v.img)||p.variants.filter(v=>v.img).sort((a,b)=>lum(a)-lum(b))[0];
const m=dark?st.img(dark.img).then(st.cut):Promise.reject(new Error("no image"));this.#masks.set(i,m),m.catch(()=>this.#masks.delete(i));return m}
#compose(i,c){const p=this.products[i],key=i+"|"+c+"|"+this.#dv;if(this.#cache.has(key))return this.#cache.get(key);const v=p.variants.find(t=>t.c===c&&t.img);if(!v)return Promise.reject(new Error("no image"));
const job=Promise.all([this.#mask(i),st.img(v.img)]).then(([m,img])=>{const W=m.W,H=m.H,cv=document.createElement("canvas");cv.width=W,cv.height=H;const g=cv.getContext("2d",{willReadFrequently:!0});g.drawImage(img,0,0,W,H);const id=g.getImageData(0,0,W,H),d=id.data;for(let k=0,q=3;k<m.a.length;k++,q+=4)d[q]=m.a[k];g.putImageData(id,0,0);
if(this.design){const r=st.AREA[p.handle]||st.AREA["orican-crew-tee"];g.globalCompositeOperation="source-atop",g.globalAlpha=.97,g.drawImage(this.design.bmp,r[0]*W,r[1]*H,r[2]*W,r[3]*H)}return new Promise((t,e)=>cv.toBlob(s=>s?t(URL.createObjectURL(s)):e(new Error("png")),"image/png"))});
this.#cache.set(key,job),job.catch(()=>this.#cache.delete(key));return job}
#paint(){const tok=++this.#tok;this.slides.forEach((e,i)=>{const s=e.querySelector(".blank-img");if(!s||!this.products[i].live)return;const c=this.#colorOf(i);this.#compose(i,c).then(u=>{tok===this.#tok&&s.getAttribute("src")!==u&&(s.src=u),s.dataset.ready="1"}).catch(()=>{const v=this.products[i].variants.find(t=>t.c===c&&t.img);v&&(s.src=v.img),s.dataset.ready="1"})});
const p=this.product,i=this.#Nt,dv=this.#dv;p.live&&(window.requestIdleCallback||(f=>setTimeout(f,300)))(()=>{let k=0;const next=()=>{const c=p.palette[k++];c&&dv===this.#dv&&this.#compose(i,c.name).catch(()=>{}).then(()=>setTimeout(next,30))};next()})}
#H(){const p=this.product,t=this.tee;this.track.style.transform=`translateX(${100*-this.#Nt}%)`,this.nameEl.textContent=t.name,this.priceEl.textContent=t.price,this.dots.forEach((e,i)=>e.setAttribute("aria-current",i===this.#Nt?"true":"false"));
p.live?this.#paint():this.tees.forEach(e=>{e.style.color=this.color.hex});const d=!!this.design;this.el.classList.toggle("has-design",d&&p.live),this.addBtn.hidden=!d||!p.live,this.addBtn.disabled=!this.variant,this.btn.classList.toggle("ghost",d&&p.live),this.btnText&&(this.btnText.nodeValue=d?"Edit design":"Customize");
this.btn.disabled=!!p.live&&!this.variant;const e=this.saved[this.#Nt];this.fav.setAttribute("aria-pressed",e),V(this.fav.firstElementChild,e?"mdi:heart":"mdi:heart-outline"),this.fav.setAttribute("aria-label",(e?"Remove ":"Save ")+p.name)}
async #design(d){if(!d||!d.imageBlob)return;try{const blob=await st.pad(d.imageBlob),bmp=await createImageBitmap(blob);this.design&&this.design.bmp.close&&this.design.bmp.close(),this.design={blob,bmp},this.#dv++;for(const j of this.#cache.values())j.then(u=>URL.revokeObjectURL(u)).catch(()=>{});this.#cache.clear();
const x=document.getElementById("closeFrame");x&&x.click(),this.note.textContent="Your design is on the shirt. Pick a color and size, then add it to your cart.",this.#H(),setTimeout(()=>this.el.scrollIntoView({behavior:"smooth",block:"center"}),60)}catch(e){console.error("ORICAN design",e)}}
async #cart(){const v=this.variant,b=this.addBtn;if(!this.design||!v)return;b.disabled=!0,b.textContent="Adding…",this.note.textContent="";
try{const{upload:u}=await import(st.API+"/orican-upload.js"),r=await u("designs/"+v.id+".png",this.design.blob,{access:"public",handleUploadUrl:st.API+"/api/upload",contentType:"image/png"}),root=window.Shopify&&Shopify.routes&&Shopify.routes.root||"/",
a=await fetch(root+"cart/add.js",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({items:[{id:v.id,quantity:1,properties:{Design:"Custom ORICAN proof",_design_url:r.url}}]})});
if(!a.ok){const e=await a.json().catch(()=>({}));throw new Error(e.description||e.message||"cart "+a.status)}location.href=root+"cart"}catch(e){console.error("ORICAN add to cart",e),b.disabled=!1,b.textContent="Add to cart",this.note.textContent="Couldn't add to cart. Please try again."}}}
